// Explicit, never autogenerated. There are four documents and their order is
// an editorial decision — how to use it, why it works that way, how it is
// built, and the reference table you look things up in. An autogenerated
// sidebar would re-sort them the moment a fifth arrives.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'userguide',
    'spec',
    'architecture',
    'canonicalization-reference',
  ],
};

export default sidebars;
