// Autogenerated, but NOT alphabetised — every position here is still an
// editorial decision, it just lives next to the file it orders instead of in
// a second list that can disagree with it.
//
// This file used to name all four documents explicitly, on the argument that
// their order is editorial and autogeneration would re-sort them. Splitting
// the user guide into 23 files made the second half of that argument stop
// holding and the first half stop scaling: `sidebar_position` in each page's
// front matter and `position` in each `_category_.json` carry the order, so
// autogeneration reproduces it exactly, and a page added without a position
// lands at the end rather than displacing anything.
//
// Where the order actually comes from:
//   docs/*.md                        sidebar_position 2, 3, 4
//   docs/userguide/_category_.json   position 1, and the index page as its link
//   docs/userguide/<group>/…         _category_.json per group, then per page

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
